version: 0.2

phases:
    pre_build:
        commands:
            - sam validate
            - npm install
            - npm run lint
            - npm run prettier
            - npm run test
            - npm --prefix ./lambda-layers/utils/nodejs install
    build:
        commands:
            - sam package --template-file template.yaml --output-template-file deploy.yaml --s3-bucket $SAM_S3_BUCKET
            - sam deploy --template-file deploy.yaml --stack-name $SAM_STACK_NAME --capabilities CAPABILITY_IAM --region $AWS_REGION
