AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 10

Resources:
    CreateUserFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            FunctionName: CreateUser
            CodeUri: functions/create-user
            Handler: main.lambdaHandler
            Role: arn:aws:iam::063257378709:role/CrudLambdasRunner
            Runtime: nodejs12.x
            Layers:
                - !Ref UtilsLayer
            Events:
                CreateUser:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /user
                        Method: post
    GetUsersFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            FunctionName: GetUsers
            CodeUri: functions/get-users
            Handler: main.lambdaHandler
            Role: arn:aws:iam::063257378709:role/CrudLambdasRunner
            Runtime: nodejs12.x
            Events:
                GetUsers:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /user
                        Method: get
                        
    DeleteUserFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            FunctionName: DeleteUser
            CodeUri: functions/delete-user
            Handler: main.lambdaHandler
            Role: arn:aws:iam::063257378709:role/CrudLambdasRunner
            Runtime: nodejs12.x
            Events:
                DeleteUser:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /user/{id}
                        Method: delete
                        
    UpdateUserFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            FunctionName: UpdateUser
            CodeUri: functions/update-user
            Handler: main.lambdaHandler
            Role: arn:aws:iam::063257378709:role/CrudLambdasRunner
            Runtime: nodejs12.x
            Events:
                UpdateUser:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /user/{id}
                        Method: put

    UsersTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: auc_users
            AttributeDefinitions:
                - AttributeName: Id
                  AttributeType: S
                - AttributeName: name
                  AttributeType: S
                - AttributeName: email
                  AttributeType: S
            KeySchema:
                - AttributeName: id
                  KeyType: HASH
            ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5
    
    UtilsLayer: 
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: Utils
            Description: Layer that includes some javascript helpers
            ContentUri: lambda-layers/utils
            CompatibleRuntimes:
                - nodejs12.x
            LicenseInfo: MIT
            RetentionPolicy: Delete
    

Outputs:
    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    GetUsersApi:
        Description: 'API Gateway endpoint URL for Prod stage for Get users function'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/user/'
    GetUsersFunction:
        Description: 'GetUsersFunction Lambda Function ARN'
        Value: !GetAtt GetUsersFunction.Arn
        
    CreateUserApi:
        Description: 'API Gateway endpoint URL for Prod stage for Create user function'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/user/'
    CreateUserFunction:
        Description: 'CreateUserFunction Lambda Function ARN'
        Value: !GetAtt CreateUserFunction.Arn
        
    DeleteUserApi:
        Description: 'API Gateway endpoint URL for Prod stage for Delete user function'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/user/'
    DeleteUserFunction:
        Description: 'DeleteUserFunction Lambda Function ARN'
        Value: !GetAtt DeleteUserFunction.Arn
        
    UpdateUserApi:
        Description: 'API Gateway endpoint URL for Prod stage for Update user function'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/user/'
    UpdateUserFunction:
        Description: 'UpdateUserFunction Lambda Function ARN'
        Value: !GetAtt UpdateUserFunction.Arn
        
    UtilsLayerARN:
        Value: !Ref UtilsLayer
        Description: UtilsLayer ARN
        Export:
            Name: utils-layer-arn-2
